// Wish list items sourced from GoWish — https://gowish.com/wishlists/1xYDtn8wCvkaHNop
export const WISHLIST_ITEMS = [
  // ── Books ──
  { id: 1, name: 'Family Dynamic: A Journey of Mystery and Sibling', category: 'other', price: 18, priority: 'medium', link: 'https://www.amazon.com/Family-Dynamic-Journey-Mystery-Sibling/dp/0593137906', image: '', notes: 'Book.', acquired: false },

  // ── Fragrances ──
  { id: 2, name: 'Dior Ambre Nuit Eau de Parfum', category: 'fashion', price: 280, priority: 'high', link: 'https://www.dior.com/en_us/beauty/products/ambre-nuit-E000000204.html', image: '', notes: 'Maison Christian Dior collection. Warm amber fragrance.', acquired: false },
  { id: 3, name: 'Ex Nihilo Blue Talisman EDP 1.7oz', category: 'fashion', price: 295, priority: 'high', link: 'https://www.neimanmarcus.com/p/ex-nihilo-blue-talisman-eau-de-parfum-1-7-oz-prod266390059', image: '', notes: 'Niche fragrance. Neiman Marcus exclusive.', acquired: false },
  { id: 4, name: 'Guerlain Cuir Beluga EDP 3.3oz', category: 'fashion', price: 370, priority: 'high', link: 'https://www.neimanmarcus.com/p/guerlain-lart-la-matiere-cuir-beluga-eau-de-parfum-3-3-oz-prod250500846', image: '', notes: "L'Art & La Matiere collection. Leather-forward luxury scent.", acquired: false },
  { id: 5, name: "Byredo Bal d'Afrique Absolu de Parfum", category: 'fashion', price: 340, priority: 'high', link: 'https://www.byredo.com/us_en/p/bal-dafrique-absolu-de-parfum', image: '', notes: 'African-inspired niche fragrance by Byredo.', acquired: false },
  { id: 6, name: 'Montblanc Explorer EDP 30ml', category: 'fashion', price: 62, priority: 'medium', link: 'https://www.montblanc.com/en-us/explorer-eau-de-parfums-30-ml-MB124071.html', image: '', notes: "Men's daily driver fragrance.", acquired: false },

  // ── LEGO ──
  { id: 7, name: 'LEGO Chevrolet Camaro Z/28 (10304)', category: 'other', price: 170, priority: 'high', link: 'https://www.lego.com/en-us/product/chevrolet-camaro-z28-10304', image: '', notes: 'LEGO Icons set. 1,458 pieces. Would go next to the real Camaro.', acquired: false },
  { id: 8, name: 'LEGO Porsche 911 (10295)', category: 'other', price: 150, priority: 'medium', link: 'https://www.lego.com/en-us/product/porsche-911-10295', image: '', notes: 'LEGO Creator Expert. Turbo/Targa build options.', acquired: false },

  // ── Katanas ──
  { id: 9, name: 'Black Moon Soul Cutter Katana (Sharp)', category: 'other', price: 200, priority: 'medium', link: 'https://minikatana.com/collections/anime-replicas/products/black-moon-soul-cutter-1045-carbon-steel-sharp-katana', image: 'https://minikatana.com/cdn/shop/files/5F0A4661-Editar.jpg?v=1717707630', notes: "Ichigo Kurosaki Bankai Katana replica from Bleach. Sleek, battle-ready 1045 carbon steel. Captures the raw, condensed power of Ichigo's Bankai form.", acquired: false },
  { id: 10, name: 'Flame Katana — Rengoku Replica (Sharp)', category: 'other', price: 180, priority: 'medium', link: 'https://minikatana.com/collections/deluxe-anime-replicas-1045-carbon-steel-battle-ready-sharpened/products/flame-1045-carbon-steel-sharp-katana', image: 'https://minikatana.com/cdn/shop/files/Battle-Ready_Rengoku_Katana_SHARP__2-Edit.jpg?v=1761327224', notes: 'Full-tang Flame 1045 Carbon Steel Katana. Handcrafted for collectors. Free US shipping over $35.', acquired: false },

  // ── Percival ──
  { id: 11, name: 'Percival Casa Martini Polo — Forest', category: 'fashion', price: 135, priority: 'medium', link: 'https://www.percivalclo.com/products/casa-martini-polo-cotton-forest', image: '', notes: 'Cotton polo shirt in forest green. Percival London.', acquired: false },
  { id: 12, name: 'Percival Casa Martini Polo — Espresso', category: 'fashion', price: 135, priority: 'medium', link: 'https://www.percivalclo.com/products/casa-martini-polo-cotton-espresso', image: '', notes: 'Cotton polo shirt in espresso brown. Percival London.', acquired: false },

  // ── Buck Mason ──
  { id: 13, name: 'Buck Mason Black Pima Classic Tee', category: 'fashion', price: 36, priority: 'low', link: 'https://www.buckmason.com/products/black-pima-classic-tee', image: 'https://cdn.shopify.com/s/files/1/0123/5065/2473/files/BM11030.101BLK-pima-straight-hem-tee_1024x.jpg?v=1695400307', notes: 'Classic fit crewneck tee in premium, long-staple USA-grown Supima cotton. Made at BM Knitting Mills in Mohnton, PA.', acquired: false },

  // ── Dandy Del Mar ──
  { id: 14, name: 'Dandy Del Mar The Tropez Shirt — Burnt Sienna', category: 'fashion', price: 59, priority: 'medium', link: 'https://dandydelmar.com/products/the-tropez-shirt-burnt-sienna-orange-terry-cloth-shirt-patch-pocket', image: 'https://dandydelmar.com/cdn/shop/files/DDM-SS24-On-model-261220237616.jpg?v=1762563264', notes: "Premium terry cloth staple designed for effortless leisure. Lightweight with a relaxed tailored fit that captures the timeless romance of the Cote d'Azur.", acquired: false },
  { id: 15, name: 'Dandy Del Mar The Cannes Tee — Arbequina Green', category: 'fashion', price: 48, priority: 'low', link: 'https://dandydelmar.com/collections/mens-leisure-wear/products/the-cannes-tee-arbequina-green-waffle-knit-short-sleeve-tshirt', image: 'https://dandydelmar.com/cdn/shop/files/DDM-SS24-On-model-261220238709.jpg?v=1762563265', notes: 'Elevates the classic crew neck with a sophisticated waffle knit texture and stylish contrast ringer neck and sleeves. Medium-weight, breathable, soft airy handle.', acquired: false },
  { id: 16, name: 'Dandy Del Mar The Dominica Crochet Shirt — Burnt Sienna', category: 'fashion', price: 89, priority: 'medium', link: 'https://dandydelmar.com/collections/mens-leisure-wear/products/the-dominica-crochet-shirt-burnt-sienna-stripe', image: 'https://dandydelmar.com/cdn/shop/products/Dominica_Sienna_4x5_1.jpg?v=1762563267', notes: 'Combines elegance and comfort for any destination. Crafted from soft, breathable cotton crochet with a dapper, relaxed fit that moves with you.', acquired: false },
  { id: 17, name: 'Dandy Del Mar The Grenadine Shirt — Truffle White', category: 'fashion', price: 69, priority: 'low', link: 'https://dandydelmar.com/collections/mens-leisure-wear/products/the-grenadine-shirt-truffle-white-crinkle-gauze-woven-shirt', image: 'https://dandydelmar.com/cdn/shop/files/DDMSS24Onmodel261220238791.jpg?v=1762563263', notes: 'Timeless, jazz-inspired aesthetic. Lightweight 100% cotton crinkle gauze. Casually refined travel shirt with sophisticated notch collar.', acquired: false },
  { id: 18, name: 'Dandy Del Mar The Sebastian Polo — Onyx Black', category: 'fashion', price: 68, priority: 'medium', link: 'https://dandydelmar.com/products/the-sebastian-buttonless-polo-shirt-onyx-black', image: 'https://dandydelmar.com/cdn/shop/files/258A0727-2.jpg?v=1764090733', notes: 'Masterfully tailored Italian summer sweater. Reimagines the classic polo with sophisticated Mediterranean flair. Premium 100% cotton.', acquired: false },

  // ── OAS Company ──
  { id: 19, name: 'OAS Plateau Polo Terry Shirt', category: 'fashion', price: 170, priority: 'medium', link: 'https://oascompany.com/us/plateau-polo-terry-shirt', image: 'https://images.oascompany.com/product-images/1077_7602d5f6f9-plateau-polo-terry-shirt-a-original.jpg?auto=format&q=80&w=600', notes: 'Terry cloth polo shirt by OAS Company.', acquired: false },
  { id: 20, name: 'OAS Puzzle Cuba Terry Shirt', category: 'fashion', price: 160, priority: 'low', link: 'https://oascompany.com/us/puzzle-cuba-terry-shirt', image: 'https://images.oascompany.com/product-images/974_6bfc6f03e3-puzzle-cuba-terry-shirt-7003-89-25_a_-original.jpg?auto=format&q=80&w=600', notes: 'Beige and navy terry shirt in heavyweight woven cotton with geometric pattern. Relaxed fit, resort collar. 100% cotton. Made in Portugal.', acquired: false },
  { id: 21, name: 'OAS Atlas Cuba Net Shirt', category: 'fashion', price: 140, priority: 'low', link: 'https://oascompany.com/us/atlas-cuba-net-shirt', image: 'https://images.oascompany.com/product-images/1140_890c70c302-atlas-cuba-net-shirt-original.jpg?auto=format&q=80&w=600', notes: 'Net/mesh Cuban shirt by OAS Company.', acquired: false },
  { id: 22, name: 'OAS Vista Girona Linen Shirt', category: 'fashion', price: 155, priority: 'medium', link: 'https://oascompany.com/us/vista-girona-linen-shirt', image: 'https://oas.centracdn.net/client/dynamic/images/1125_acccf136de-girona-velour-shirt-1-original.jpg?auto=format&q=80&w=600', notes: 'Linen Cuban shirt by OAS Company.', acquired: false },
  { id: 23, name: 'OAS Nebula Cuba Linen Shirt', category: 'fashion', price: 155, priority: 'low', link: 'https://oascompany.com/us/nebula-cuba-linen-shirt', image: 'https://images.oascompany.com/product-images/1126_3862acd049-nebula-cuba-linen-shirt-7012-03-a_-original.jpg?auto=format&q=80&w=600', notes: 'Linen Cuban shirt by OAS Company.', acquired: false },
  { id: 24, name: 'OAS Hypnotise Cuba Net Shirt', category: 'fashion', price: 140, priority: 'low', link: 'https://oascompany.com/us/hypnotise-cuba-net-shirt', image: 'https://images.oascompany.com/product-images/1142_e1895f06e7-hypnotise-cuba-net-shirt-a_-original.jpg?auto=format&q=80&w=600', notes: 'Knitted cotton shirt in black and beige bobbinet pattern. Relaxed fit with resort collar and curved hemline. 100% cotton. Made in Portugal.', acquired: false },

  // ── AS Colour ──
  { id: 25, name: 'AS Colour Heavy Faded Tee', category: 'fashion', price: 30, priority: 'low', link: 'https://ascolour.com/mens-heavy-faded-tee-5082/', image: 'https://cdn11.bigcommerce.com/s-hsi95a83fz/products/790/images/24456/5082_HEAVY_FADED_TEE_FADED_CARDINAL_THUMB___26284.1763601199.386.513.jpg?c=1', notes: 'Premium heavyweight faded tee. Functional blank clothing built to last.', acquired: false },

  // ── Bound ──
  { id: 26, name: 'Bound Cedar Brown Corduroy Trousers', category: 'fashion', price: 70, priority: 'medium', link: 'https://wearebound.co.uk/products/cedar-brown-corduroy-trousers', image: 'https://wearebound.co.uk/cdn/shop/files/42761-2.jpg?v=1696929379', notes: 'New and improved fabric of the best-selling cord trouser silhouette. Softer, longer lasting, no shine.', acquired: false },
  { id: 27, name: 'Bound Seville Linen Trousers — Olive', category: 'fashion', price: 65, priority: 'medium', link: 'https://wearebound.co.uk/products/seville-linen-trousers-olive', image: 'https://wearebound.co.uk/cdn/shop/products/Seville_Linen_Trouser_Khaki_01.jpg?v=1677662418', notes: 'Lightweight breathable linen, perfect for summer. Slightly tapered with ankle crop. Elasticated waist, pre-wash softened.', acquired: false },

  // ── Tech / Home ──
  { id: 28, name: 'Sanus TV Mount for Sonos Beam', category: 'tech', price: 40, priority: 'medium', link: 'https://www.sonos.com/en-us/shop/sanus-tv-mount-beam', image: 'https://media.sonos.com/images/znqtjj88/production/e05cb6599ae02dc390b29b673ece552e0cead118-968x808.png?q=75&fit=clip&auto=format', notes: 'Keeps your mounted TV and Sonos Beam together for ideal home theater. Compatible with most TV mount brands. Smart Latch technology provides 12 inches of depth adjustment.', acquired: false },
  { id: 29, name: 'Kanto SP32PL Speaker Stands (Pair, Black)', category: 'tech', price: 120, priority: 'medium', link: 'https://www.turntablelab.com/products/kanto-sp32pl-speaker-stands-black-pair', image: 'https://www.turntablelab.com/cdn/shop/products/kanto-SP32PL.jpg?v=1762273699&width=600', notes: '32" height floor speaker stands for YU4/YU6/TUK speakers. From TurntableLab.', acquired: false },
  { id: 30, name: 'Lululemon Aim Boxer 3-Pack', category: 'fashion', price: 78, priority: 'low', link: 'https://shop.lululemon.com/p/men-underwear/Aim-Boxer-3-Pack/_/prod9270824', image: '', notes: "Men's underwear. 3 pack.", acquired: false },
]
