export const APP_REGISTRY = [
  {
    id: 'about',
    label: 'README.txt',
    icon: '📄',
    component: () => import('./About/About.jsx'),
    defaultSize: { width: 480, height: 360 },
    defaultPosition: { x: 80, y: 60 },
    openOnBoot: true,
    pinned: true,
    auth: false,
  },
  {
    id: 'projects',
    label: 'Projects',
    icon: '📁',
    component: () => import('./Projects/Projects.jsx'),
    defaultSize: { width: 560, height: 420 },
    defaultPosition: { x: 120, y: 80 },
    openOnBoot: false,
    pinned: true,
    auth: false,
  },
  {
    id: 'terminal',
    label: 'Terminal',
    icon: '💻',
    component: () => import('./Terminal/Terminal.jsx'),
    defaultSize: { width: 500, height: 340 },
    defaultPosition: { x: 200, y: 140 },
    openOnBoot: false,
    pinned: true,
    auth: false,
  },
  {
    id: 'solitaire',
    label: 'Solitaire',
    icon: '🃏',
    component: () => import('./Solitaire/Solitaire.jsx'),
    defaultSize: { width: 620, height: 560 },
    defaultPosition: { x: 100, y: 40 },
    openOnBoot: false,
    pinned: false,
    auth: false,
  },
]
