export const APP_REGISTRY = [
  // ── Content ──
  {
    id: 'about',
    label: 'README.sh',
    icon: 'terminal',
    component: () => import('./About/About.jsx'),
    defaultSize: { width: 600, height: 450 },
    defaultPosition: { x: Math.max(0, Math.floor((typeof window !== 'undefined' ? window.innerWidth : 1200) / 2 - 300)), y: Math.max(0, Math.floor((typeof window !== 'undefined' ? window.innerHeight : 800) / 2 - 250)) },
    openOnBoot: true,
    pinned: true,
    auth: false,
    category: null, // top-level
    hideFromDesktop: true, // opens on boot; no need for a desktop icon
  },
  {
    id: 'aboutme',
    label: 'About',
    icon: 'computer',
    component: () => import('./AboutMe/AboutMe.jsx'),
    defaultSize: { width: 560, height: 480 },
    defaultPosition: { x: 140, y: 60 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'projects',
    label: 'Projects',
    icon: 'folder',
    component: () => import('./Projects/Projects.jsx'),
    defaultSize: { width: 560, height: 420 },
    defaultPosition: { x: 120, y: 80 },
    openOnBoot: false,
    pinned: true,
    auth: false,
    category: null,
  },
  {
    id: 'blog',
    label: 'Blog',
    icon: 'blog',
    component: () => import('./Blog/Blog.jsx'),
    defaultSize: { width: 520, height: 440 },
    defaultPosition: { x: 100, y: 60 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'pictures',
    label: 'Pictures',
    icon: 'pictures',
    component: () => import('./Pictures/Pictures.jsx'),
    defaultSize: { width: 500, height: 400 },
    defaultPosition: { x: 110, y: 50 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'videos',
    label: 'Videos',
    icon: 'videos',
    component: () => import('./Videos/Videos.jsx'),
    defaultSize: { width: 520, height: 420 },
    defaultPosition: { x: 120, y: 60 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'messageboard',
    label: 'Message Board',
    icon: 'message',
    component: () => import('./MessageBoard/MessageBoard.jsx'),
    defaultSize: { width: 540, height: 440 },
    defaultPosition: { x: 130, y: 70 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'guestbook',
    label: 'Guestbook',
    icon: 'guestbook',
    component: () => import('./Guestbook/Guestbook.jsx'),
    defaultSize: { width: 440, height: 420 },
    defaultPosition: { x: 150, y: 60 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'music',
    label: 'Music',
    icon: 'music',
    component: () => import('./Music/Music.jsx'),
    defaultSize: { width: 440, height: 360 },
    defaultPosition: { x: 140, y: 80 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'reviews',
    label: 'Reviews',
    icon: 'reviews',
    component: () => import('./Reviews/Reviews.jsx'),
    defaultSize: { width: 520, height: 440 },
    defaultPosition: { x: 110, y: 50 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'restaurants',
    label: 'The Food List',
    icon: 'restaurant',
    component: () => import('./Restaurants/Restaurants.jsx'),
    defaultSize: { width: 500, height: 440 },
    defaultPosition: { x: 130, y: 60 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'carmods',
    label: 'Car Mods',
    icon: 'car',
    component: () => import('./CarMods/CarMods.jsx'),
    defaultSize: { width: 480, height: 440 },
    defaultPosition: { x: 120, y: 50 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'wishlist',
    label: 'Wish List',
    icon: 'wish',
    component: () => import('./WishList/WishList.jsx'),
    defaultSize: { width: 480, height: 420 },
    defaultPosition: { x: 130, y: 60 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'trips',
    label: 'Travel Log',
    icon: 'travel',
    component: () => import('./Trips/Trips.jsx'),
    defaultSize: { width: 520, height: 440 },
    defaultPosition: { x: 110, y: 50 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'digest',
    label: 'Daily Digest',
    icon: 'digest',
    component: () => import('./Digest/Digest.jsx'),
    defaultSize: { width: 520, height: 480 },
    defaultPosition: { x: 130, y: 50 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'manifestations',
    label: 'Manifestations',
    icon: 'cookie',
    component: () => import('./Manifestations/Manifestations.jsx'),
    defaultSize: { width: 520, height: 420 },
    defaultPosition: { x: 150, y: 70 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'email',
    label: 'ChemMail',
    icon: 'email',
    component: () => import('./Email/Email.jsx'),
    defaultSize: { width: 580, height: 440 },
    defaultPosition: { x: 100, y: 50 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: null,
  },
  {
    id: 'terminal',
    label: 'Terminal',
    icon: 'terminal',
    component: () => import('./Terminal/Terminal.jsx'),
    defaultSize: { width: 500, height: 340 },
    defaultPosition: { x: 200, y: 140 },
    openOnBoot: false,
    pinned: true,
    auth: false,
    category: null,
  },

  // ── Stats ──
  {
    id: 'stats',
    label: 'Scoreboard',
    icon: 'trophy',
    component: () => import('./Stats/Stats.jsx'),
    defaultSize: { width: 520, height: 460 },
    defaultPosition: { x: 120, y: 40 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
  },

  // ── Games ──
  {
    id: 'solitaire',
    label: 'Solitaire',
    icon: 'cards',
    component: () => import('./Solitaire/Solitaire.jsx'),
    defaultSize: { width: 620, height: 560 },
    defaultPosition: { x: 100, y: 40 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
  },
  {
    id: 'minesweeper',
    label: 'Minesweeper',
    icon: 'bomb',
    component: () => import('./Minesweeper/Minesweeper.jsx'),
    defaultSize: { width: 280, height: 380 },
    defaultPosition: { x: 160, y: 60 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
  },
  {
    id: 'chess',
    label: 'Chess',
    icon: 'chess',
    component: () => import('./Chess/Chess.jsx'),
    defaultSize: { width: 540, height: 480 },
    defaultPosition: { x: 100, y: 20 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
  },
  {
    id: 'pong',
    label: 'Table Tennis',
    icon: 'paddle',
    component: () => import('./Pong/Pong.jsx'),
    defaultSize: { width: 560, height: 400 },
    defaultPosition: { x: 140, y: 60 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
  },
  {
    id: 'asteroids',
    label: 'Asteroids',
    icon: 'rocket',
    component: () => import('./Asteroids/Asteroids.jsx'),
    defaultSize: { width: 560, height: 440 },
    defaultPosition: { x: 120, y: 50 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
  },
  {
    id: 'pacman',
    label: 'Pac-Man',
    icon: 'ghost',
    component: () => import('./Pacman/Pacman.jsx'),
    defaultSize: { width: 460, height: 430 },
    defaultPosition: { x: 130, y: 30 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
  },
  {
    id: 'spaceinvaders',
    label: 'Space Invaders',
    icon: 'alien',
    component: () => import('./SpaceInvaders/SpaceInvaders.jsx'),
    defaultSize: { width: 520, height: 480 },
    defaultPosition: { x: 110, y: 40 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
  },
  {
    id: 'arkanoid',
    label: 'Arkanoid',
    icon: 'brick',
    component: () => import('./Arkanoid/Arkanoid.jsx'),
    defaultSize: { width: 440, height: 520 },
    defaultPosition: { x: 130, y: 30 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
  },
  {
    id: 'fighter',
    label: "Rock'em Sock'em",
    icon: 'robot',
    component: () => import('./Fighter/Fighter.jsx'),
    defaultSize: { width: 560, height: 420 },
    defaultPosition: { x: 100, y: 30 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
    mobile: false,
  },

  // ── Mobile-friendly games ──
  {
    id: 'tetris',
    label: 'Tetris',
    icon: 'tetris',
    component: () => import('./Tetris/Tetris.jsx'),
    defaultSize: { width: 380, height: 520 },
    defaultPosition: { x: 140, y: 30 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
    mobile: true,
  },
  {
    id: 'sudoku',
    label: 'Sudoku',
    icon: 'sudoku',
    component: () => import('./Sudoku/Sudoku.jsx'),
    defaultSize: { width: 400, height: 520 },
    defaultPosition: { x: 130, y: 30 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
    mobile: true,
  },
  {
    id: 'doodlejump',
    label: 'Doodle Jump',
    icon: 'doodlejump',
    component: () => import('./DoodleJump/DoodleJump.jsx'),
    defaultSize: { width: 320, height: 480 },
    defaultPosition: { x: 150, y: 30 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
    mobile: true,
  },
  {
    id: 'fruitninja',
    label: 'Fruit Ninja',
    icon: 'fruitninja',
    component: () => import('./FruitNinja/FruitNinja.jsx'),
    defaultSize: { width: 360, height: 480 },
    defaultPosition: { x: 140, y: 30 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
    mobile: true,
  },
  {
    id: 'snake',
    label: 'Snake',
    icon: 'snake',
    component: () => import('./Snake/Snake.jsx'),
    defaultSize: { width: 360, height: 380 },
    defaultPosition: { x: 140, y: 60 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
    mobile: true,
  },
  {
    id: '2048',
    label: '2048',
    icon: 'twentyfortyeight',
    component: () => import('./TwentyFortyEight/TwentyFortyEight.jsx'),
    defaultSize: { width: 380, height: 480 },
    defaultPosition: { x: 130, y: 40 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
    mobile: true,
  },
  {
    id: 'flappybird',
    label: 'Flappy Bird',
    icon: 'flappybird',
    component: () => import('./FlappyBird/FlappyBird.jsx'),
    defaultSize: { width: 320, height: 480 },
    defaultPosition: { x: 150, y: 30 },
    openOnBoot: false,
    pinned: false,
    auth: false,
    category: 'games',
    mobile: true,
  },
  // ── Hidden (admin only, not in menus) ──
  {
    id: 'admin',
    label: 'Admin Panel',
    icon: 'settings',
    component: () => import('./Admin/Admin.jsx'),
    defaultSize: { width: 600, height: 500 },
    defaultPosition: { x: 100, y: 40 },
    openOnBoot: false,
    pinned: false,
    auth: true,
    category: 'hidden',
  },
]

// Category definitions for the Start Menu
export const MENU_CATEGORIES = [
  { id: 'games', label: 'Games', icon: 'games' },
]
